version: '3'

services:
  web:
    build: .
    #command: ./manage.py test
    #command: uwsgi --ini dcashier/uwsgi.ini
    command: ./manage.py runserver 0.0.0.0:8081
    ports:
      - "8000:8081"
    volumes:
      - .:/code
